// 插件配置默认值 — 纯数据，无运行时依赖
export const DEFAULT_DLTAG_CRON = '0 */6 * * *'

export const defaults = {
  enabled: false,
  local_plugin_repo: '',
  fusion_notify_enabled: true,
  fusion_card_create_cron: '5 0 * * *',
  fusion_card_refresh_cron: '0 * * * *',
  health_check_enabled: true,
  health_check_schedule_enabled: true,
  health_check_cron: '0 */6 * * *',
  health_check_items: [],
  health_check_database_targets: ['current'],
  health_check_storage_targets: ['storages', 'config', 'download', 'library'],
  health_check_directory_targets: ['config', 'plugin', 'download', 'library'],
  health_check_storage_threshold: 85,
  health_check_notify_type: 'Plugin',
  subscribe_reminder_enabled: true,
  subscribe_reminder_schedule_enabled: true,
  subscribe_reminder_cron: '0 9 * * *',
  subscribe_reminder_subtype: ['movie', 'tv'],
  subscribe_reminder_msgtype: 'Subscribe',
  site_stat_enabled: true,
  site_stat_schedule_enabled: true,
  site_stat_cron: '0 8 * * *',
  site_stat_dashboard_type: 'today',
  site_stat_notify_type: 'Plugin',
  log_clean_enabled: false,
  log_clean_schedule_enabled: false,
  log_clean_cron: '0 3 * * 1',
  log_clean_rows: 300,
  log_clean_selected_ids: [],
  log_clean_notify: true,
  log_clean_notify_type: 'Plugin',
  backup_enabled: false,
  backup_notify: false,
  backup_notify_type: 'Plugin',
  backup_cron: '0 4 * * 1',
  backup_keep_count: 5,
  backup_path: '/config/plugins/Signal/Backup',
  backup_webdav_digest_auth: false,
  backup_webdav_disable_check: false,
  backup_webdav_hostname: '',
  backup_webdav_login: '',
  backup_webdav_password: '',
  backup_webdav_max_count: 5,
  mp_update_enabled: false,
  mp_update_schedule_enabled: false,
  mp_update_cron: '0 9 * * *',
  mp_update_types: ['后端', '前端'],
  market_update_enabled: false,
  market_update_schedule_enabled: false,
  market_update_cron: '0 9 * * *',
  market_update_strategy: 'check',
  market_update_install_ids: [],
  market_update_exclude_ids: [],
  update_scheduled_notify: false,
  update_notify_type: 'Plugin',
  plugin_uninstall_ids: [],
  plugin_uninstall_remove_plugin: true,
  plugin_uninstall_clear_config: true,
  plugin_uninstall_clear_data: true,
  plugin_uninstall_delete_source: false,
  seedclean_enabled: false,
  seedclean_schedule_enabled: false,
  seedclean_cron: '0 */12 * * *',
  seedclean_action: 'pause',
  seedclean_downloaders: [],
  seedclean_size: '',
  seedclean_ratio: '',
  seedclean_time: '',
  seedclean_upspeed: '',
  seedclean_labels: '',
  seedclean_pathkeywords: '',
  seedclean_trackerkeywords: '',
  seedclean_errorkeywords: '',
  seedclean_torrentstates: '',
  seedclean_trtorrentstates: '',
  seedclean_torrentcategorys: '',
  seedclean_samedata: false,
  seedclean_mponly: false,
  seedclean_notify: true,
  seedclean_notify_type: 'Plugin',
  subfill_enabled: false,
  subfill_details: [],
  subfill_category_enabled: false,
  subfill_category_confs: '',
  msgnotify_enabled: false,
  msgnotify_types: [],
  msgnotify_servers: [],
  msgnotify_notify_type: 'MediaServer',
  dltag_enabled: false,
  dltag_downloaders: [],
  dltag_tasks: ['tagging', 'seeding', 'cleanup'],
  dltag_cron: DEFAULT_DLTAG_CRON,
  dltag_listen_download: true,
  dltag_listen_source_file: false,
  dltag_prefix: '',
  dltag_all_tags: [],
  dltag_excluded_tags: [],
  dltag_not_select_all_tag: '非全',
  dltag_tracker_mappings: '',
  dltag_source_delete_strategy: 'delayed',
  dltag_scheduled_notify: false,
  dltag_notify_type: 'Plugin',
}
