import {
  mdiArrowDown,
  mdiArrowUp,
  mdiBroom,
  mdiCalendarCheck,
  mdiCalendarToday,
  mdiCardAccountDetailsOutline,
  mdiCardPlusOutline,
  mdiChartPie,
  mdiCheckCircle,
  mdiCloudUploadOutline,
  mdiCog,
  mdiDatabase,
  mdiEye,
  mdiHeartPulse,
  mdiLeaf,
  mdiRefresh,
  mdiRss,
  mdiTagMultiple,
  mdiTrashCanOutline,
  mdiYinYang,
} from '@mdi/js'

export const signalIcons = {
  arrowDown: mdiArrowDown,
  arrowUp: mdiArrowUp,
  broom: mdiBroom,
  calendarCheck: mdiCalendarCheck,
  calendarToday: mdiCalendarToday,
  cardAccount: mdiCardAccountDetailsOutline,
  cardPlus: mdiCardPlusOutline,
  chartPie: mdiChartPie,
  checkCircle: mdiCheckCircle,
  cloudUpload: mdiCloudUploadOutline,
  cog: mdiCog,
  database: mdiDatabase,
  eye: mdiEye,
  heartPulse: mdiHeartPulse,
  leaf: mdiLeaf,
  refresh: mdiRefresh,
  rss: mdiRss,
  tagMultiple: mdiTagMultiple,
  trash: mdiTrashCanOutline,
  yinYang: mdiYinYang,
}
