import { createApp, defineComponent, h } from 'vue'
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'
import 'vuetify/styles'
import PreviewApp from './preview/PreviewApp.vue'
import CronField from '../features/config/components/fields/CronField.vue'
import { CronVuetify } from '@vue-js-cron/vuetify'
import '@vue-js-cron/vuetify/dist/vuetify.css'
import { VBtn } from 'vuetify/components/VBtn'
import * as labsComponents from 'vuetify/labs/components'
import { aliases as mdiSvgAliases } from 'vuetify/iconsets/mdi-svg'
import {
  mdiAccountOutline,
  mdiAlertCircleOutline,
  mdiAlertOutline,
  mdiAlphaMBoxOutline,
  mdiArchiveArrowUpOutline,
  mdiArchiveSearchOutline,
  mdiAutoFix,
  mdiBackupRestore,
  mdiBell,
  mdiBellBadgeOutline,
  mdiBellCogOutline,
  mdiBellOutline,
  mdiBellRingOutline,
  mdiBlockHelper,
  mdiBroom,
  mdiCalendarClock,
  mdiCardAccountDetailsOutline,
  mdiCardPlusOutline,
  mdiChartBar,
  mdiChartLine,
  mdiChartLineVariant,
  mdiChartPie,
  mdiCheck,
  mdiCheckCircleOutline,
  mdiCheckDecagramOutline,
  mdiChevronRight,
  mdiClose,
  mdiCloudOutline,
  mdiCloudRefreshOutline,
  mdiCloudSearchOutline,
  mdiCloudSyncOutline,
  mdiCloudUploadOutline,
  mdiCodeTags,
  mdiCogOutline,
  mdiContentCopy,
  mdiContentSaveOutline,
  mdiCubeOutline,
  mdiDatabaseArrowUpOutline,
  mdiDatabaseCheckOutline,
  mdiDatabaseOutline,
  mdiDeleteOutline,
  mdiDeleteSweepOutline,
  mdiDownload,
  mdiDownloadCircleOutline,
  mdiDownloadNetworkOutline,
  mdiDownloadOutline,
  mdiEmailOutline,
  mdiFileDocumentRemoveOutline,
  mdiFileEyeOutline,
  mdiFilterOutline,
  mdiFolderArrowUpOutline,
  mdiFolderCheckOutline,
  mdiFolderKeyOutline,
  mdiFolderOutline,
  mdiFormTextbox,
  mdiFormatListBulleted,
  mdiFormatListChecks,
  mdiFormatListNumbered,
  mdiGauge,
  mdiHarddisk,
  mdiHeartPulse,
  mdiHistory,
  mdiInformationOutline,
  mdiLayersOutline,
  mdiLayersTripleOutline,
  mdiLightningBoltOutline,
  mdiLinkVariant,
  mdiLockCheckOutline,
  mdiLockOutline,
  mdiMessageBadgeOutline,
  mdiMovieOpenCogOutline,
  mdiMovieOpenOutline,
  mdiNewspaperVariantOutline,
  mdiPencilOutline,
  mdiPercent,
  mdiPlay,
  mdiPlusCircleOutline,
  mdiPowerStandby,
  mdiPuzzle,
  mdiPuzzleCheckOutline,
  mdiPuzzleOutline,
  mdiPuzzlePlusOutline,
  mdiPuzzleRemoveOutline,
  mdiRefresh,
  mdiRocketLaunchOutline,
  mdiRssBox,
  mdiSatelliteUplink,
  mdiScaleBalance,
  mdiSendOutline,
  mdiServer,
  mdiServerNetwork,
  mdiShieldAlertOutline,
  mdiShieldCheckOutline,
  mdiShieldHalfFull,
  mdiShieldOutline,
  mdiShieldSyncOutline,
  mdiSignal,
  mdiSync,
  mdiTagMultipleOutline,
  mdiTagOutline,
  mdiTagPlusOutline,
  mdiTelevision,
  mdiTelevisionPlay,
  mdiTimerCogOutline,
  mdiTimerOutline,
  mdiTuneVariant,
  mdiUpdate,
  mdiViewDashboardOutline,
  mdiViewGridOutline,
  mdiWeb,
  mdiWeight
} from '@mdi/js'

// Vuetify defaults - copied from official MP frontend src/plugins/vuetify/defaults.ts
// so preview components render with the same styling as the real MoviePilot host.
const vuetifyDefaults = {
  IconBtn: { icon: true, color: 'default', variant: 'text', VIcon: { size: 24 } },
  VAlert: { VBtn: { color: undefined } },
  VAvatar: { variant: 'flat', VIcon: { size: 24 } },
  VBadge: { color: 'primary' },
  VBtn: { color: 'primary', elevation: 0 },
  VCard: { elevation: 0, rounded: 'lg' },
  VMenu: { elevation: 0, transition: 'mp-popover-transition' },
  VChip: { elevation: 0 },
  VBottomSheet: { elevation: 0, transition: 'mp-bottom-sheet-transition' },
  VDialog: { elevation: 0, rounded: 'lg', transition: 'mp-dialog-transition' },
  VExpansionPanels: { elevation: 0 },
  VList: { color: 'primary', elevation: 0 },
  VListItem: { rounded: 'md' },
  VPagination: { activeColor: 'primary' },
  VTabs: { color: 'primary', VSlideGroup: { showArrows: true } },
  VTooltip: { location: 'top', transition: 'mp-popover-transition' },
  VCheckboxBtn: { color: 'primary', hideDetails: 'auto' },
  VCheckbox: { color: 'primary', hideDetails: 'auto' },
  VRadioGroup: { color: 'primary', hideDetails: 'auto' },
  VRadio: { color: 'primary', hideDetails: 'auto' },
  VSelect: { variant: 'outlined', color: 'primary', hideDetails: 'auto', menuProps: { elevation: 0 } },
  VRangeSlider: { color: 'primary', density: 'comfortable', thumbLabel: true, hideDetails: 'auto' },
  VRating: { color: 'rgba(var(--v-theme-on-background),0.23)', activeColor: 'warning', halfIncrements: true },
  VProgressCircular: { color: 'primary' },
  VSlider: { color: 'primary', hideDetails: 'auto' },
  VTextField: { variant: 'outlined', color: 'primary', hideDetails: 'auto' },
  VAutocomplete: { variant: 'outlined', color: 'primary', hideDetails: 'auto' },
  VCombobox: { variant: 'outlined', color: 'primary', hideDetails: 'auto', menuProps: { elevation: 0 } },
  VFileInput: { variant: 'outlined', color: 'primary', hideDetails: 'auto' },
  VTextarea: { variant: 'outlined', color: 'primary', hideDetails: 'auto' },
  VSwitch: { color: 'primary', hideDetails: 'auto' },
}

const lightThemeVariables = {
  'code-color': '#D400FF',
  'overlay-scrim-background': '#3A3541',
  'overlay-scrim-opacity': 0.5,
  'hover-opacity': 0.04,
  'focus-opacity': 0.1,
  'selected-opacity': 0.12,
  'activated-opacity': 0.1,
  'pressed-opacity': 0.14,
  'dragged-opacity': 0.1,
  'border-color': '#3A3541',
  'table-header-background': '#F9FAFC',
  'custom-background': '#F9F8F9',
  'shadow-key-umbra-opacity': 'rgba(var(--v-theme-on-surface), 0.08)',
  'shadow-key-penumbra-opacity': 'rgba(var(--v-theme-on-surface), 0.12)',
  'shadow-key-ambient-opacity': 'rgba(var(--v-theme-on-surface), 0.04)',
}

const darkThemeVariables = {
  'code-color': '#d400ff',
  'overlay-scrim-background': '#191D21',
  'overlay-scrim-opacity': 0.6,
  'hover-opacity': 0.04,
  'focus-opacity': 0.1,
  'selected-opacity': 0.12,
  'activated-opacity': 0.1,
  'pressed-opacity': 0.14,
  'dragged-opacity': 0.1,
  'border-color': '#E7E3FC',
  'table-header-background': '#14161F',
  'custom-background': '#373452',
  'shadow-key-umbra-opacity': 'rgba(20, 18, 33, 0.08)',
  'shadow-key-penumbra-opacity': 'rgba(20, 18, 33, 0.12)',
  'shadow-key-ambient-opacity': 'rgba(20, 18, 33, 0.04)',
}

const purpleThemeVariables = {
  'code-color': '#d400ff',
  'overlay-scrim-background': '#2C2942',
  'overlay-scrim-opacity': 0.6,
  'hover-opacity': 0.04,
  'focus-opacity': 0.1,
  'selected-opacity': 0.12,
  'activated-opacity': 0.1,
  'pressed-opacity': 0.14,
  'dragged-opacity': 0.1,
  'border-color': '#E7E3FC',
  'table-header-background': '#3D3759',
  'custom-background': '#373452',
  'shadow-key-umbra-opacity': 'rgba(20, 18, 33, 0.08)',
  'shadow-key-penumbra-opacity': 'rgba(20, 18, 33, 0.12)',
  'shadow-key-ambient-opacity': 'rgba(20, 18, 33, 0.04)',
}

const transparentThemeVariables = {
  'code-color': '#6D9EEB',
  'overlay-scrim-background': '0, 0, 0',
  'overlay-scrim-opacity': 0.7,
  'hover-opacity': 0.1,
  'focus-opacity': 0.15,
  'selected-opacity': 0.2,
  'activated-opacity': 0.15,
  'pressed-opacity': 0.2,
  'dragged-opacity': 0.15,
  'border-color': '#E7E3FC',
  'table-header-background': 'rgba(30, 30, 30, 0.24)',
  'custom-background': 'rgba(30, 30, 30, 0.24)',
  'card-background': 'rgba(30, 30, 30, 0.24)',
  'shadow-key-umbra-opacity': 'rgba(0, 0, 0, 0.07)',
  'shadow-key-penumbra-opacity': 'rgba(0, 0, 0, 0.1)',
  'shadow-key-ambient-opacity': 'rgba(0, 0, 0, 0.05)',
}

const localMdiPaths = {
  'mdi-account-outline': mdiAccountOutline,
  'mdi-alert-circle-outline': mdiAlertCircleOutline,
  'mdi-alert-outline': mdiAlertOutline,
  'mdi-alpha-m-box-outline': mdiAlphaMBoxOutline,
  'mdi-archive-arrow-up-outline': mdiArchiveArrowUpOutline,
  'mdi-archive-search-outline': mdiArchiveSearchOutline,
  'mdi-auto-fix': mdiAutoFix,
  'mdi-backup-restore': mdiBackupRestore,
  'mdi-bell': mdiBell,
  'mdi-bell-badge-outline': mdiBellBadgeOutline,
  'mdi-bell-cog-outline': mdiBellCogOutline,
  'mdi-bell-outline': mdiBellOutline,
  'mdi-bell-ring-outline': mdiBellRingOutline,
  'mdi-block-helper': mdiBlockHelper,
  'mdi-broom': mdiBroom,
  'mdi-calendar-clock': mdiCalendarClock,
  'mdi-card-account-details-outline': mdiCardAccountDetailsOutline,
  'mdi-card-plus-outline': mdiCardPlusOutline,
  'mdi-chart-bar': mdiChartBar,
  'mdi-chart-line': mdiChartLine,
  'mdi-chart-line-variant': mdiChartLineVariant,
  'mdi-chart-pie': mdiChartPie,
  'mdi-check': mdiCheck,
  'mdi-check-circle-outline': mdiCheckCircleOutline,
  'mdi-check-decagram-outline': mdiCheckDecagramOutline,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-close': mdiClose,
  'mdi-cloud-outline': mdiCloudOutline,
  'mdi-cloud-refresh-outline': mdiCloudRefreshOutline,
  'mdi-cloud-search-outline': mdiCloudSearchOutline,
  'mdi-cloud-sync-outline': mdiCloudSyncOutline,
  'mdi-cloud-upload-outline': mdiCloudUploadOutline,
  'mdi-code-tags': mdiCodeTags,
  'mdi-cog-outline': mdiCogOutline,
  'mdi-content-copy': mdiContentCopy,
  'mdi-content-save-outline': mdiContentSaveOutline,
  'mdi-cube-outline': mdiCubeOutline,
  'mdi-database-arrow-up-outline': mdiDatabaseArrowUpOutline,
  'mdi-database-check-outline': mdiDatabaseCheckOutline,
  'mdi-database-outline': mdiDatabaseOutline,
  'mdi-delete-outline': mdiDeleteOutline,
  'mdi-delete-sweep-outline': mdiDeleteSweepOutline,
  'mdi-download': mdiDownload,
  'mdi-download-circle-outline': mdiDownloadCircleOutline,
  'mdi-download-network-outline': mdiDownloadNetworkOutline,
  'mdi-download-outline': mdiDownloadOutline,
  'mdi-email-outline': mdiEmailOutline,
  'mdi-file-document-remove-outline': mdiFileDocumentRemoveOutline,
  'mdi-file-eye-outline': mdiFileEyeOutline,
  'mdi-filter-outline': mdiFilterOutline,
  'mdi-folder-arrow-up-outline': mdiFolderArrowUpOutline,
  'mdi-folder-check-outline': mdiFolderCheckOutline,
  'mdi-folder-key-outline': mdiFolderKeyOutline,
  'mdi-folder-outline': mdiFolderOutline,
  'mdi-form-textbox': mdiFormTextbox,
  'mdi-format-list-bulleted': mdiFormatListBulleted,
  'mdi-format-list-checks': mdiFormatListChecks,
  'mdi-format-list-numbered': mdiFormatListNumbered,
  'mdi-gauge': mdiGauge,
  'mdi-harddisk': mdiHarddisk,
  'mdi-heart-pulse': mdiHeartPulse,
  'mdi-heart-pulse-solid': mdiHeartPulse,
  'mdi-history': mdiHistory,
  'mdi-information-outline': mdiInformationOutline,
  'mdi-layers-outline': mdiLayersOutline,
  'mdi-layers-triple-outline': mdiLayersTripleOutline,
  'mdi-lightning-bolt-outline': mdiLightningBoltOutline,
  'mdi-link-variant': mdiLinkVariant,
  'mdi-lock-check-outline': mdiLockCheckOutline,
  'mdi-lock-outline': mdiLockOutline,
  'mdi-message-badge-outline': mdiMessageBadgeOutline,
  'mdi-movie-open-cog-outline': mdiMovieOpenCogOutline,
  'mdi-movie-open-outline': mdiMovieOpenOutline,
  'mdi-newspaper-variant-outline': mdiNewspaperVariantOutline,
  'mdi-pencil-outline': mdiPencilOutline,
  'mdi-percent': mdiPercent,
  'mdi-play': mdiPlay,
  'mdi-plus-circle-outline': mdiPlusCircleOutline,
  'mdi-power-standby': mdiPowerStandby,
  'mdi-puzzle': mdiPuzzle,
  'mdi-puzzle-check-outline': mdiPuzzleCheckOutline,
  'mdi-puzzle-outline': mdiPuzzleOutline,
  'mdi-puzzle-plus-outline': mdiPuzzlePlusOutline,
  'mdi-puzzle-remove-outline': mdiPuzzleRemoveOutline,
  'mdi-refresh': mdiRefresh,
  'mdi-rocket-launch-outline': mdiRocketLaunchOutline,
  'mdi-rss-box': mdiRssBox,
  'mdi-satellite-uplink': mdiSatelliteUplink,
  'mdi-scale-balance': mdiScaleBalance,
  'mdi-send-outline': mdiSendOutline,
  'mdi-server': mdiServer,
  'mdi-server-network': mdiServerNetwork,
  'mdi-shield-alert-outline': mdiShieldAlertOutline,
  'mdi-shield-check-outline': mdiShieldCheckOutline,
  'mdi-shield-half-full': mdiShieldHalfFull,
  'mdi-shield-outline': mdiShieldOutline,
  'mdi-shield-sync-outline': mdiShieldSyncOutline,
  'mdi-signal': mdiSignal,
  'mdi-sync': mdiSync,
  'mdi-tag-multiple-outline': mdiTagMultipleOutline,
  'mdi-tag-outline': mdiTagOutline,
  'mdi-tag-plus-outline': mdiTagPlusOutline,
  'mdi-television': mdiTelevision,
  'mdi-television-play': mdiTelevisionPlay,
  'mdi-timer-cog-outline': mdiTimerCogOutline,
  'mdi-timer-outline': mdiTimerOutline,
  'mdi-tune-variant': mdiTuneVariant,
  'mdi-update': mdiUpdate,
  'mdi-view-dashboard-outline': mdiViewDashboardOutline,
  'mdi-view-grid-outline': mdiViewGridOutline,
  'mdi-web': mdiWeb,
  'mdi-weight': mdiWeight
}

const LocalMdiIcon = defineComponent({
  name: 'LocalMdiIcon',
  inheritAttrs: false,
  props: {
    icon: { type: [String, Array], default: '' },
    tag: { type: String, default: 'i' },
  },
  setup(props, { attrs }) {
    return () => {
      const rawIcon = props.icon
      const paths = Array.isArray(rawIcon)
        ? rawIcon
        : localMdiPaths[rawIcon]
          || (typeof rawIcon === 'string' && rawIcon.startsWith('svg:') ? rawIcon.slice(4) : null)
          || localMdiPaths['mdi-cog-outline']
          || mdiCogOutline
      const pathNodes = Array.isArray(paths)
        ? paths.map(path => Array.isArray(path)
          ? h('path', { d: path[0], 'fill-opacity': path[1] })
          : h('path', { d: path }))
        : [h('path', { d: paths })]

      return h(props.tag, attrs, [
        h('svg', {
          class: 'v-icon__svg',
          xmlns: 'http://www.w3.org/2000/svg',
          viewBox: '0 0 24 24',
          role: 'img',
          'aria-hidden': 'true',
        }, pathNodes),
      ])
    }
  },
})

// Local preview uses the same mdi-* names as MoviePilot, but renders them
// from local SVG paths so screenshot gates do not depend on external icon APIs.
const alertTypeIcon = {
  success: 'mdi-check-circle-outline',
  info: 'mdi-information-outline',
  warning: 'mdi-alert-outline',
  error: 'mdi-alert-circle-outline',
}

const localMdi = {
  component: LocalMdiIcon,
}

const icons = {
  defaultSet: 'localMdi',
  aliases: Object.assign({}, mdiSvgAliases, alertTypeIcon),
  sets: {
    localMdi,
  },
}

const vuetify = createVuetify({
  components: {
    ...components,
    ...labsComponents,
  },
  directives,
  aliases: {
    IconBtn: VBtn,
  },
  defaults: vuetifyDefaults,
  icons,
  theme: {
    defaultTheme: 'transparent',
    themes: {
      transparent: {
        dark: true,
        colors: {
          'primary': '#A370F7',
          'secondary': '#8A8D93',
          'on-secondary': '#FFFFFF',
          'success': '#66BB6A',
          'info': '#42A5F5',
          'warning': '#FFA726',
          'error': '#EF5350',
          'on-primary': '#FFFFFF',
          'on-success': '#FFFFFF',
          'on-warning': '#FFFFFF',
          'background': '#1C1C1C',
          'on-background': '#E7E3FC',
          'surface': 'rgba(30, 30, 30, 0.24)',
          'on-surface': '#E7E3FC',
          'surface-variant': 'rgba(30, 30, 30, 0.16)',
          'on-surface-variant': 'rgba(255, 255, 255, 0.65)',
          'grey-50': 'rgba(42, 46, 66, 0.15)',
          'grey-100': 'rgba(71, 67, 96, 0.15)',
          'grey-200': 'rgba(74, 80, 114, 0.15)',
          'grey-300': 'rgba(94, 102, 146, 0.15)',
          'grey-400': 'rgba(121, 131, 187, 0.15)',
          'grey-500': 'rgba(134, 146, 208, 0.15)',
          'grey-600': 'rgba(170, 179, 222, 0.15)',
          'grey-700': 'rgba(182, 190, 227, 0.15)',
          'grey-800': 'rgba(207, 211, 236, 0.15)',
          'grey-900': 'rgba(231, 233, 246, 0.15)',
          'perfect-scrollbar-thumb': 'rgba(158, 158, 190, 0.4)',
          'skin-bordered-background': 'rgba(30, 30, 30, 0.24)',
          'skin-bordered-surface': 'rgba(30, 30, 30, 0.24)',
          'card-background': 'rgba(30, 30, 30, 0.24)',
        },
        variables: transparentThemeVariables,
      },
      dark: {
        dark: true,
        colors: {
          'primary': '#6E66ED',
          'secondary': '#8A8D93',
          'on-secondary': '#FFFFFF',
          'success': '#56CA00',
          'info': '#16B1FF',
          'warning': '#FFB400',
          'error': '#FF4C51',
          'on-primary': '#FFFFFF',
          'on-success': '#FFFFFF',
          'on-warning': '#FFFFFF',
          'background': '#0E1116',
          'on-background': '#E7E3FC',
          'surface': '#14161F',
          'on-surface': '#E7E3FC',
          'grey-50': '#2A2E42',
          'grey-100': '#474360',
          'grey-200': '#4A5072',
          'grey-300': '#5E6692',
          'grey-400': '#7983BB',
          'grey-500': '#8692D0',
          'grey-600': '#AAB3DE',
          'grey-700': '#B6BEE3',
          'grey-800': '#CFD3EC',
          'grey-900': '#E7E9F6',
          'perfect-scrollbar-thumb': '#4A5072',
          'skin-bordered-background': '#312d4b',
          'skin-bordered-surface': '#312d4b',
        },
        variables: darkThemeVariables,
      },
      light: {
        dark: false,
        colors: {
          'primary': '#9155FD',
          'secondary': '#8A8D93',
          'on-secondary': '#FFFFFF',
          'success': '#56CA00',
          'info': '#16B1FF',
          'warning': '#FFB400',
          'error': '#FF4C51',
          'on-primary': '#FFFFFF',
          'on-success': '#FFFFFF',
          'on-warning': '#FFFFFF',
          'background': '#F4F5FA',
          'on-background': '#3A3541',
          'on-surface': '#3A3541',
          'grey-50': '#FAFAFA',
          'grey-100': '#F0F2F8',
          'grey-200': '#EEEEEE',
          'grey-300': '#E0E0E0',
          'grey-400': '#BDBDBD',
          'grey-500': '#9E9E9E',
          'grey-600': '#757575',
          'grey-700': '#616161',
          'grey-800': '#424242',
          'grey-900': '#212121',
          'perfect-scrollbar-thumb': '#DBDADE',
          'skin-bordered-background': '#FFFFFF',
          'skin-bordered-surface': '#FFFFFF',
        },
        variables: lightThemeVariables,
      },
      purple: {
        dark: true,
        colors: {
          'primary': '#9155FD',
          'secondary': '#8A8D93',
          'on-secondary': '#FFFFFF',
          'success': '#56CA00',
          'info': '#16B1FF',
          'warning': '#FFB400',
          'error': '#FF4C51',
          'on-primary': '#FFFFFF',
          'on-success': '#FFFFFF',
          'on-warning': '#FFFFFF',
          'background': '#28243D',
          'on-background': '#E7E3FC',
          'surface': '#312D4B',
          'on-surface': '#E7E3FC',
          'grey-50': '#2A2E42',
          'grey-100': '#474360',
          'grey-200': '#4A5072',
          'grey-300': '#5E6692',
          'grey-400': '#7983BB',
          'grey-500': '#8692D0',
          'grey-600': '#AAB3DE',
          'grey-700': '#B6BEE3',
          'grey-800': '#CFD3EC',
          'grey-900': '#E7E9F6',
          'perfect-scrollbar-thumb': '#4A5072',
          'skin-bordered-background': '#312d4b',
          'skin-bordered-surface': '#312d4b',
        },
        variables: purpleThemeVariables,
      },
    },
  },
})

const app = createApp(PreviewApp)

// Local preview registers host-equivalent Cron semantics (not a VTextField fake).
app.component('VCronVuetify', CronVuetify)
app.component('VCronField', CronField)

app.use(vuetify).mount('#app')
